# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoBanco',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bancoAsign', models.CharField(max_length=5)),
                ('tipoServicio', models.CharField(max_length=2)),
                ('envio', models.CharField(max_length=4)),
                ('secuencia', models.PositiveIntegerField(default=0)),
                ('archivoNombre', models.CharField(max_length=25, null=True, blank=True)),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ArchivoBancoDetailN',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipoRegistro', models.CharField(default=b'N', max_length=1, blank=True)),
                ('idCompania', models.CharField(max_length=15)),
                ('secuencia', models.CharField(max_length=7)),
                ('secuenciaTrans', models.CharField(max_length=7)),
                ('cuentaDestino', models.CharField(max_length=20)),
                ('tipoCuentaDestino', models.CharField(max_length=1)),
                ('monedaDestino', models.CharField(default=b'214', max_length=3)),
                ('codBancoDestino', models.CharField(default=b'10101070', max_length=8)),
                ('digiVerBancoDestino', models.CharField(default=b'8', max_length=1)),
                ('codigoOperacion', models.CharField(default=b'22', max_length=2)),
                ('montoTransaccion', models.CharField(max_length=13)),
                ('tipoIdentificacion', models.CharField(default=b'CE', max_length=2)),
                ('identificacion', models.CharField(max_length=15)),
                ('nombre', models.CharField(default=b'', max_length=35)),
                ('numeroReferencia', models.CharField(default=b'', max_length=12, blank=True)),
                ('descrpEstadoDestino', models.CharField(default=b'', max_length=40, blank=True)),
                ('fechaVencimiento', models.CharField(default=b'', max_length=4, blank=True)),
                ('formaContacto', models.CharField(default=b' ', max_length=1)),
                ('emailBenef', models.CharField(default=b'', max_length=40, blank=True)),
                ('faxTelefonoBenef', models.CharField(default=b'', max_length=12, blank=True)),
                ('filler', models.CharField(default=b'00', max_length=2)),
                ('numeroAut', models.CharField(default=b'', max_length=15, blank=True)),
                ('codRetornoRemoto', models.CharField(default=b'   ', max_length=3)),
                ('codRazonRemoto', models.CharField(default=b'   ', max_length=3)),
                ('codRazonInterno', models.CharField(default=b'   ', max_length=3)),
                ('procTransaccion', models.CharField(default=b' ', max_length=1)),
                ('estatusTransaccion', models.CharField(default=b' ', max_length=2)),
                ('filler2', models.CharField(default=b'', max_length=52, blank=True)),
                ('lineaFormateadaN', models.CharField(max_length=320, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ArchivoBancoDetailR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipoRegistro', models.CharField(default=b'R', max_length=1)),
                ('idCompania', models.CharField(max_length=15)),
                ('secuencia', models.CharField(max_length=7)),
                ('secuenciaTrans', models.CharField(max_length=7)),
                ('numeroCtaDestino', models.CharField(max_length=20)),
                ('numeroDocumento', models.CharField(max_length=15)),
                ('tipoDocumento', models.CharField(max_length=2)),
                ('fechaDocumento', models.CharField(max_length=8)),
                ('montoDocumento', models.CharField(max_length=13)),
                ('montoDescuento', models.CharField(max_length=11)),
                ('montoImpuesto', models.CharField(max_length=11)),
                ('netoDocumento', models.CharField(max_length=13)),
                ('descripcion', models.CharField(max_length=50)),
                ('filler', models.CharField(max_length=146, blank=True)),
                ('lineaFormateadaR', models.CharField(max_length=319)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ArchivoBancoHeader',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipoRegistro', models.CharField(max_length=1)),
                ('idCompania', models.CharField(max_length=15)),
                ('nombreCompania', models.CharField(max_length=35)),
                ('secuencia', models.CharField(max_length=7)),
                ('tipoServicio', models.CharField(max_length=2)),
                ('fechaEfectiva', models.CharField(max_length=8)),
                ('cantidadDB', models.CharField(max_length=11)),
                ('montoTotalDB', models.CharField(max_length=13)),
                ('cantidadCR', models.CharField(max_length=11)),
                ('montoTotalCR', models.CharField(max_length=13)),
                ('numeroAfiliacion', models.CharField(max_length=15, blank=True)),
                ('fecha', models.CharField(max_length=8)),
                ('hora', models.CharField(max_length=4)),
                ('correo', models.CharField(max_length=40)),
                ('estatus', models.CharField(max_length=1, blank=True)),
                ('cuentaEmpresa', models.CharField(max_length=1)),
                ('filler', models.CharField(max_length=107, blank=True)),
                ('lineaFormateadaH', models.CharField(max_length=292, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Autorizador',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('clave', models.CharField(max_length=4)),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usuario'],
                'verbose_name_plural': 'Config 3.1) Autorizadores',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=100)),
                ('digitoVerificador', models.CharField(default=b'8', max_length=1)),
                ('codigoOperacion', models.CharField(default=b'22', max_length=2)),
                ('estatus', models.CharField(default=b'A', max_length=1, choices=[(b'A', b'Activo'), (b'I', b'Inactivo')])),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Config 2.1) Bancos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CategoriaPrestamo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=70)),
                ('montoDesde', models.DecimalField(verbose_name=b'Monto Desde', max_digits=18, decimal_places=2, blank=True)),
                ('montoHasta', models.DecimalField(verbose_name=b'Monto Hasta', max_digits=18, decimal_places=2, blank=True)),
                ('tipo', models.CharField(max_length=2, choices=[(b'OD', b'Orden de Despacho'), (b'PR', b'Prestamo'), (b'SC', b'SuperCoop')])),
                ('interesAnualSocio', models.DecimalField(null=True, verbose_name=b'Intereses Anual Socio %', max_digits=6, decimal_places=2, blank=True)),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Categoria de Prestamo',
                'verbose_name_plural': 'Config 6.1) Categorias de Prestamos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('descripcion',),
                'verbose_name_plural': 'Config 4.2) Categorias de Productos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CoBeneficiario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(null=True, blank=True)),
                ('sector', models.CharField(max_length=40, null=True, blank=True)),
                ('ciudad', models.CharField(max_length=40, null=True, blank=True)),
                ('cedula', models.CharField(max_length=15, null=True, blank=True)),
                ('telefono', models.CharField(max_length=40, null=True, blank=True)),
                ('celular', models.CharField(max_length=40, null=True, blank=True)),
                ('parentesco', models.CharField(default=b'O', max_length=1, choices=[(b'C', b'Conyugue'), (b'H', b'Hijo(a)'), (b'T', b'Tio(a)'), (b'A', b'Abuelo(a)'), (b'O', b'Otro')])),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Co-Beneficiario',
                'verbose_name_plural': 'Co-Beneficiarios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usuario', models.CharField(max_length=10)),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'ordering': ['usuario'],
                'verbose_name_plural': 'Config 3.2) Cobradores',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CuotaOrdenes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('montoDesde', models.DecimalField(verbose_name=b'Monto Desde', max_digits=18, decimal_places=2)),
                ('montoHasta', models.DecimalField(verbose_name=b'Monto Hasta', max_digits=18, decimal_places=2)),
                ('cantidadQuincenas', models.PositiveIntegerField(verbose_name=b'Cantidad de Quincenas')),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-montoDesde'],
                'verbose_name': 'Cuota de Ordenes',
                'verbose_name_plural': 'Config 6.3) Cuotas de Ordenes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('montoDesde', models.DecimalField(verbose_name=b'Monto Desde', max_digits=18, decimal_places=2)),
                ('montoHasta', models.DecimalField(verbose_name=b'Monto Hasta', max_digits=18, decimal_places=2)),
                ('cantidadQuincenas', models.PositiveIntegerField(verbose_name=b'Cantidad de Quincenas')),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-montoDesde'],
                'verbose_name': 'Cuota de Prestamo',
                'verbose_name_plural': 'Config 6.2) Cuotas de Prestamos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('centroCosto', models.CharField(max_length=10, verbose_name=b'Centro de Costo')),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Config 1.4) Departamentos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DocumentoCuentas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('accion', models.CharField(max_length=1, choices=[(b'D', b'Debito'), (b'C', b'Credito')])),
                ('cuenta', models.ForeignKey(to='cuenta.Cuentas')),
            ],
            options={
                'ordering': ['documento', 'cuenta'],
                'verbose_name': 'Documento relacionado a Cuentas',
                'verbose_name_plural': 'Config 7.2) Documentos relacionados a Cuentas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50)),
                ('rnc', models.CharField(max_length=15, null=True, blank=True)),
                ('cuentaBanco', models.CharField(max_length=1, null=True)),
                ('bancoAsign', models.CharField(max_length=5, null=True, blank=True)),
                ('correoHeader', models.CharField(max_length=40, null=True, blank=True)),
                ('estatus', models.CharField(default=b'A', max_length=1, choices=[(b'A', b'Activo'), (b'I', b'Inactivo')])),
            ],
            options={
                'verbose_name_plural': 'Config 2.2) Empresas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=10)),
                ('descripcionLarga', models.CharField(max_length=150, blank=True)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Config 2.6) Localidades',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('valor', models.CharField(default=b'true', max_length=5)),
                ('tipo', models.CharField(default=b'P', max_length=1, choices=[(b'P', b'Principal'), (b'S', b'Secundario')])),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Config 3.3) Opciones',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfilCod', models.CharField(unique=True, max_length=15, verbose_name=b'Codigo Perfil')),
            ],
            options={
                'ordering': ['perfilCod'],
                'verbose_name_plural': 'Config 3.4) Perfiles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('mes', models.CharField(default=b'01', max_length=2, choices=[(b'01', b'Enero'), (b'02', b'Febrero'), (b'03', b'Marzo'), (b'04', b'Abril'), (b'05', b'Mayo'), (b'06', b'Junio'), (b'07', b'Julio'), (b'08', b'Agosto'), (b'09', b'Septiembre'), (b'10', b'Octubre'), (b'11', b'Noviembre'), (b'12', b'Diciembre')])),
                ('agno', models.CharField(max_length=4, verbose_name=b'Agno')),
                ('estatus', models.CharField(default=b'A', max_length=1, choices=[(b'A', b'Activo'), (b'C', b'Cerrado')])),
            ],
            options={
                'ordering': ['-agno'],
                'verbose_name_plural': 'Config 7.3) Periodos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(unique=True, max_length=10, editable=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(max_digits=12, decimal_places=2)),
                ('costo', models.DecimalField(null=True, max_digits=12, decimal_places=2, blank=True)),
                ('foto', models.ImageField(null=True, upload_to=b'productos', blank=True)),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(to='administracion.CategoriaProducto', null=True)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Config 4.1) Productos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=50)),
                ('estatus', models.CharField(default=b'A', max_length=1, choices=[(b'A', b'Activo'), (b'I', b'Inactivo')])),
            ],
            options={
                'verbose_name_plural': 'Config 2.3) Representantes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion', models.TextField(blank=True)),
                ('sector', models.CharField(max_length=40, blank=True)),
                ('telefono', models.CharField(max_length=40, blank=True)),
                ('celular', models.CharField(max_length=40, blank=True)),
                ('ciudad', models.CharField(max_length=40, blank=True)),
                ('cedula', models.CharField(max_length=20, blank=True)),
                ('sexo', models.CharField(default=b'M', max_length=1, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')])),
                ('estadoCivil', models.CharField(default=b'S', max_length=1, verbose_name=b'Estado Civil', choices=[(b'S', b'Soltero(a)'), (b'C', b'Casado(a)'), (b'U', b'Union Libre')])),
                ('pasaporte', models.CharField(max_length=20, verbose_name=b'Pasaporte No.', blank=True)),
                ('fechaIngresoCoop', models.DateField(verbose_name=b'Fecha de Ingreso Coop.')),
                ('fechaIngresoEmpresa', models.DateField(verbose_name=b'Fecha de Ingreso Empresa')),
                ('correo', models.EmailField(max_length=75, blank=True)),
                ('estatus', models.CharField(default=b'S', max_length=2, choices=[(b'S', b'Socio'), (b'E', b'Empleado'), (b'I', b'Inactivo')])),
                ('salario', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('cuentaBancaria', models.CharField(max_length=20, null=True, verbose_name=b'Cuenta Bancaria', blank=True)),
                ('tipoCuentaBancaria', models.CharField(default=b'1', max_length=1, null=True, verbose_name=b'Tipo Cuenta Bancaria', blank=True)),
                ('foto', models.ImageField(null=True, upload_to=b'administracion', blank=True)),
                ('nombreCompleto', models.CharField(verbose_name=b'Nombre Completo', max_length=80, editable=False)),
                ('cuotaAhorroQ1', models.DecimalField(default=0, verbose_name=b'Cuota Ahorro Q1', max_digits=12, decimal_places=2)),
                ('cuotaAhorroQ2', models.DecimalField(default=0, verbose_name=b'Cuota Ahorro Q2', max_digits=12, decimal_places=2)),
                ('datetime_server', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(to='administracion.Departamento')),
                ('localidad', models.ForeignKey(to='administracion.Localidad')),
                ('userLog', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Config 1.1) Socios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Suplidor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipoIdentificacion', models.CharField(default=b'C', max_length=2, verbose_name=b'Tipo de Identificacion', choices=[(b'CE', b'Cedula'), (b'RN', b'RNC')])),
                ('cedulaRNC', models.CharField(unique=True, max_length=25, verbose_name=b'Cedula o RNC')),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(default=b'M', max_length=1, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')])),
                ('direccion', models.TextField(blank=True)),
                ('sector', models.CharField(max_length=40, null=True, blank=True)),
                ('ciudad', models.CharField(max_length=40, null=True, blank=True)),
                ('contacto', models.CharField(max_length=50, null=True, blank=True)),
                ('telefono', models.CharField(max_length=50, null=True, blank=True)),
                ('correo', models.CharField(max_length=40, null=True, blank=True)),
                ('fax', models.CharField(max_length=50, null=True, blank=True)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=5, blank=True, null=True, verbose_name=b'Intereses %')),
                ('clase', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'S', b'SuperCoop')])),
                ('tipoCuentaBancaria', models.CharField(max_length=2, null=True, verbose_name=b'Tipo Cuenta Bancaria', blank=True)),
                ('cuentaBancaria', models.CharField(max_length=20, null=True, verbose_name=b'Cuenta Bancaria', blank=True)),
                ('estatus', models.CharField(default=b'A', max_length=1, choices=[(b'A', b'Activo'), (b'I', b'Inactivo')])),
                ('datetimeServer', models.DateTimeField(auto_now_add=True)),
                ('auxiliar', models.ForeignKey(to='cuenta.Auxiliares', null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Config 4.4) Suplidores',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Config 7.1) Tipos de Documentos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoNCGlobal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.CharField(default=b'', max_length=1, choices=[(b'1', b'NCG'), (b'2', b'NCG2')])),
                ('descripcion', models.CharField(max_length=150)),
                ('cuenta', models.ForeignKey(to='cuenta.Cuentas')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoSuplidor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Tipo de Suplidor',
                'verbose_name_plural': 'Config 4.5) Tipos de Suplidores',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=20)),
                ('nota', models.TextField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Config 4.3) Unidades',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('localidad', models.ForeignKey(to='administracion.Localidad')),
                ('perfil', models.ForeignKey(to='administracion.Perfil')),
                ('usuario', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('usuario',),
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='userextra',
            unique_together=set([('usuario', 'localidad', 'perfil')]),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='tipoSuplidor',
            field=models.ForeignKey(to='administracion.TipoSuplidor'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='suplidor',
            name='userLog',
            field=models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(to='administracion.Unidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='producto',
            name='userLog',
            field=models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opcion',
            name='perfil',
            field=models.ForeignKey(to='administracion.Perfil'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentocuentas',
            name='documento',
            field=models.ForeignKey(to='administracion.TipoDocumento'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='documentocuentas',
            unique_together=set([('documento', 'cuenta', 'accion')]),
        ),
        migrations.AddField(
            model_name='cobeneficiario',
            name='socio',
            field=models.ForeignKey(to='administracion.Socio'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='autorizador',
            name='perfil',
            field=models.ForeignKey(to='administracion.Perfil'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='autorizador',
            name='usuario',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=True,
        ),
    ]
